name: docker_builds

on:
#  pull_request:
#    branches:
#      - develop
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-push-android-image:
    name: Android
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/android
          push: true
          tags: ghcr.io/csound/csound-android:${{ env.VERSION }},ghcr.io/csound/csound-android:latest

  build-and-push-ioscross-image:
    name: ioscross
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/ioscross
          push: true
          tags: ghcr.io/csound/csound-ioscross:${{ env.VERSION }},ghcr.io/csound/csound-ioscross:latest
          build-args: |
            DOWNLOAD_URL=${{ vars.IOSCROSS_DOWNLOAD_URL }}
          secrets: |
            IOSCROSS_PASSWORD=${{ secrets.IOSCROSS_PASSWORD }}
